name: Trigger Release

on:
  workflow_dispatch:
    inputs:
      semver:
        description: "Version Bump Level"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write

jobs:
  bump:
    name: Bump Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Git Config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install cargo-edit
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-edit

      - name: Bump Version
        run: |
          cargo set-version --bump ${{ inputs.semver }}

          cargo check

          NEW_VERSION=$(grep -m1 'version = "' Cargo.toml | cut -d '"' -f 2)
          echo "NEW_VERSION=v$NEW_VERSION" >> $GITHUB_ENV

      - name: Commit and Push
        run: |
          git commit -am "chore: release ${{ env.NEW_VERSION }}"
          git tag ${{ env.NEW_VERSION }}
          git push origin master
          git push origin ${{ env.NEW_VERSION }}
